### ISSUE TITLE
Add rating to small product card

### ISSUE THREAD

**Issue by taravannheng** [taravannheng/marketsquare#74]

**Comment by kaleemullah786** [comment]
can you provide more detail on this

**Comment by taravannheng** [comment]
why?

**Comment by kaleemullah786** [comment]
i want to work on it

**Comment by taravannheng** [comment]
Simply add a rating to the product card component on the same row as the price. It should be in this format:

Rating: 4.0 ⭐️

**Comment by kaleemullah786** [comment]
I have no access to the database

**Comment by taravannheng** [comment]
Sorry, I cannot give you the connection string to my database. If you want to work on it, you can fork the backend repo which can be found in the README file. Then set up your own MongoDB atlas database. The models of the collections can be found in the backend code.

**Comment by kaleemullah786** [comment]
Alright
